config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('generation/', include('generation.urls'))
]

generation/urls.py
from datetime import datetime

from django.urls import path, register_converter
from . import views


class DateConverter:
    regex = '\d{4}-\d{2}-\d{2}T\d{2}:\d{2}Z'

    def to_python(self, value):
        # try:
        return_value = value
        # except ValueError:
        #     return_value = datetime.strptime(value, "%Y-%m-%d")
        #     return_value.replace(hour=12, minute=59)

        return return_value

    def to_url(self, value):
        return value


register_converter(DateConverter, 'dateconverter')

app_name = 'generation'
urlpatterns = [
    path('', views.index, name='index'),
    path('current/', views.current, name='current'),
    path('<dateconverter:start_date>/<dateconverter:end_date>/', views.daterange, name='daterange'),
    path('test/', views.daterangefromform, name='daterangefromform')
]

generation/models.py
from django.db import models

# Create your models here.

generation/views.py
from django.shortcuts import render
from DataModel.Generation import *


# Create your views here.

def index(request):
    return render(request, 'generation/index.html')


def current(request):
    generation = Generation()
    fig, generation_pie_chart = generation.get_generation_mix().get_pie_chart_mix()
    context = {'generation_pie_chart': generation_pie_chart}
    return render(request, 'generation/current.html', context)


def daterange(request, start_date, end_date):
    generation = Generation(start_date, end_date)
    fig, generation_pie_chart = generation.get_generation_mix().get_pie_chart_mix()
    context = {'generation_pie_chart': generation_pie_chart}
    return render(request, 'generation/current.html', context)


def daterangefromform(request):
    if request.method == "GET":
        req1 = request.GET["start_time"]+'Z'
        req2 = request.GET["end_time"]+'Z'
    return daterange(request, req1, req2)
        # generation = Generation(request.GET["start_time"] + 'Z', request.GET["end_time"] + 'Z')
    # return render(request, 'generation/current.html', context)

generation/templates/generation/current.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
<style>
body,h1,h2,h3,h4,h5 {font-family: "Poppins", sans-serif}
body {font-size:16px;}
.w3-half img{margin-bottom:-6px;margin-top:16px;opacity:0.8;cursor:pointer}
.w3-half img:hover{opacity:1}
</style>
</head>
<body>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-red w3-collapse w3-top w3-large w3-padding" style="z-index:3;width:300px;font-weight:bold;" id="mySidebar"><br>
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-button w3-hide-large w3-display-topleft" style="width:100%;font-size:22px">Close Menu</a>
  <div class="w3-container">
    <h3 class="w3-padding-64"><b>UK<br>Energy<br>Widget</b></h3>
  </div>
  <div class="w3-bar-block">
    <a href="{% url 'generation:index' %}" class="w3-bar-item w3-button w3-hover-white">Home</a>
      <a href="{% url 'generation:current' %}" class="w3-bar-item w3-button w3-hover-white">Current Energy Mix</a>
      <br>

      <label class="w3-bar-item"><u>Or enter a time range</u> </label>
<form id="flight" method = "GET" name="get_period_of_energy_mix" id="get_period_of_energy_mix" action="{%url 'generation:daterangefromform' %}">
   {% csrf_token %}
  <label class="w3-bar-item">
    Start Time <br/>
    <input type="datetime-local" name="start_time" value="Today"/>
  </label>

  <label class="w3-bar-item">
    End Time <br/>
    <input type="datetime-local" name="end_time" data-value="7" value="After one week"/>
  </label>
    <input type="submit" value="Submit" class="w3-bar-item">

</form>


  </div>
</nav>

<!-- Top menu on small screens -->
<header class="w3-container w3-top w3-hide-large w3-red w3-xlarge w3-padding">
  <a href="javascript:void(0)" class="w3-button w3-red w3-margin-right" onclick="w3_open()">☰</a>
  <span>UK Energy Widget</span>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:340px;margin-right:40px">

  <!-- Header -->
  <div class="w3-container" style="margin-top:80px" id="showcase">
    <h1 class="w3-jumbo"><b>Home</b></h1>
  </div>


  {{ generation_pie_chart | safe}}
<!-- End page content -->
</div>

<script>
// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}

// Modal Image Gallery
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
  var captionText = document.getElementById("caption");
  captionText.innerHTML = element.alt;
}
</script>

</body>
</html>

generation/templates/generation/index.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins">
<style>
body,h1,h2,h3,h4,h5 {font-family: "Poppins", sans-serif}
body {font-size:16px;}
.w3-half img{margin-bottom:-6px;margin-top:16px;opacity:0.8;cursor:pointer}
.w3-half img:hover{opacity:1}
</style>
</head>
<body>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-red w3-collapse w3-top w3-large w3-padding" style="z-index:3;width:300px;font-weight:bold;" id="mySidebar"><br>
  <a href="javascript:void(0)" onclick="w3_close()" class="w3-button w3-hide-large w3-display-topleft" style="width:100%;font-size:22px">Close Menu</a>
  <div class="w3-container">
    <h3 class="w3-padding-64"><b>UK<br>Energy<br>Widget</b></h3>
  </div>
  <div class="w3-bar-block">
    <a href="{% url 'generation:index' %}" class="w3-bar-item w3-button w3-hover-white">Home</a>
      <a href="{% url 'generation:current' %}" class="w3-bar-item w3-button w3-hover-white">Current Energy Mix</a>
      <br>

      <label class="w3-bar-item"><u>Or enter a time range</u> </label>
<form id="flight" method = "GET" name="get_period_of_energy_mix" id="get_period_of_energy_mix" action="{%url 'generation:daterangefromform' %}">
   {% csrf_token %}
  <label class="w3-bar-item">
    Start Time <br/>
    <input type="datetime-local" name="start_time" value="Today"/>
  </label>

  <label class="w3-bar-item">
    End Time <br/>
    <input type="datetime-local" name="end_time" data-value="7" value="After one week"/>
  </label>
    <input type="submit" value="Submit" class="w3-bar-item">

</form>


  </div>
</nav>

<!-- Top menu on small screens -->
<header class="w3-container w3-top w3-hide-large w3-red w3-xlarge w3-padding">
  <a href="javascript:void(0)" class="w3-button w3-red w3-margin-right" onclick="w3_open()">☰</a>
  <span>UK Energy Widget</span>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:340px;margin-right:40px">

  <!-- Header -->
  <div class="w3-container" style="margin-top:80px" id="showcase">
    <h1 class="w3-jumbo"><b>Energy Widget</b></h1>
    <hr style="width:50px;border:5px solid blue" class="w3-round">
  </div>

  <!-- Embed current energy mix -->
  {{ generation_pie_chart | safe}}

<!-- End page content -->
</div>

<script>
// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
  document.getElementById("myOverlay").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
  document.getElementById("myOverlay").style.display = "none";
}

// Modal Image Gallery
function onClick(element) {
  document.getElementById("img01").src = element.src;
  document.getElementById("modal01").style.display = "block";
  var captionText = document.getElementById("caption");
  captionText.innerHTML = element.alt;
}
</script>

</body>
</html>



<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Generation View</title>
</head>
<body>
<label for="start">Start date:</label>
<br>
<input type="date" id="start" name="trip-start"
       value="2018-07-22"
       min="2018-01-01" max="2018-12-31">

</body>
</html>